# Generated by Django 4.2.25 on 2025-10-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_document_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_label', models.CharField(default='About Equacare', max_length=100)),
                ('title', models.CharField(default='Flexible Care That Fits Your Life', max_length=200)),
                ('content_paragraph_1', models.TextField(default="Every family's needs are unique.")),
                ('content_paragraph_2', models.TextField(default='We match you with caregivers who understand your specific needs.')),
                ('preview_image', models.ImageField(help_text='Recommended size: 800x600px', upload_to='homepage/')),
                ('button_text', models.CharField(default='Learn More About Us', max_length=100)),
                ('button_link', models.CharField(default='/about/', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Preview Section',
                'verbose_name_plural': 'About Preview Section',
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Caring Support When You Need It Most', max_length=200)),
                ('subtitle', models.TextField(default="We know life can be challenging, and we're here to make it easier.")),
                ('hero_image', models.ImageField(help_text='Recommended size: 1920x1080px', upload_to='homepage/')),
                ('button_text_1', models.CharField(default='Call Now: (515) 508-1556', max_length=100)),
                ('button_link_1', models.CharField(default='tel:+15155081556', max_length=200)),
                ('button_text_2', models.CharField(default='Request Free Consultation', max_length=100)),
                ('button_link_2', models.CharField(default='/contact/', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
    ]
