# Generated by Django 4.2.25 on 2025-10-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_aboutpreview_herosection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default="Let Us Know What's On Your Mind", max_length=200)),
                ('subtitle', models.TextField(default='Request a no-obligation, in-home consultation')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Form Section',
                'verbose_name_plural': 'Contact Form Section',
            },
        ),
        migrations.CreateModel(
            name='CTASection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Ready to Talk?', max_length=200)),
                ('subtitle', models.TextField(default='It all starts with a conversation. Call us or send a message above.')),
                ('button_text', models.CharField(default='Call Now: (515) 508-1556', max_length=100)),
                ('button_link', models.CharField(default='tel:+15155081556', max_length=200)),
                ('show_button', models.BooleanField(default=True, help_text='Show/hide the call button')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CTA Section',
                'verbose_name_plural': 'CTA Section',
            },
        ),
        migrations.CreateModel(
            name='ServicesHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_label', models.CharField(default='Our Services', max_length=100)),
                ('title', models.CharField(default='How We Can Help', max_length=200)),
                ('subtitle', models.TextField(default="From a few hours a week to around-the-clock care, we're here with a helping hand")),
                ('button_text', models.CharField(default='View All Services', max_length=100)),
                ('button_link', models.CharField(default='/services/', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Services Section Header',
                'verbose_name_plural': 'Services Section Header',
            },
        ),
    ]
