# Generated by Django 4.2.25 on 2025-10-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_contactformsection_ctasection_servicesheader'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformsection',
            name='email_label',
            field=models.CharField(default='Email:', max_length=100),
        ),
        migrations.AddField(
            model_name='contactformsection',
            name='error_message',
            field=models.TextField(default='An error occurred. Please try again or call us directly.'),
        ),
        migrations.AddField(
            model_name='contactformsection',
            name='message_label',
            field=models.CharField(default='Message:', max_length=100),
        ),
        migrations.AddField(
            model_name='contactformsection',
            name='name_label',
            field=models.CharField(default='Name:', max_length=100),
        ),
        migrations.AddField(
            model_name='contactformsection',
            name='phone_label',
            field=models.CharField(default='Phone:', max_length=100),
        ),
        migrations.AddField(
            model_name='contactformsection',
            name='subject_label',
            field=models.CharField(default='Subject:', max_length=100),
        ),
        migrations.AddField(
            model_name='contactformsection',
            name='subject_options',
            field=models.TextField(default='Request Free Consultation\nGeneral Inquiry\nServices Information', help_text='Enter one subject option per line'),
        ),
        migrations.AddField(
            model_name='contactformsection',
            name='submit_button_text',
            field=models.CharField(default='Send Message', max_length=100),
        ),
        migrations.AddField(
            model_name='contactformsection',
            name='success_message',
            field=models.TextField(default='Thank you for contacting us! We will get back to you soon.'),
        ),
    ]
