# Generated by Django 4.2.25 on 2025-10-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_contactformsection_email_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Equacare LLC', max_length=200)),
                ('tagline', models.CharField(blank=True, default='Professional Non-Medical Home Care Services', max_length=300)),
                ('phone', models.CharField(default='(515) 508-1556', max_length=20)),
                ('phone_link', models.CharField(default='+15155081556', help_text='Phone number for tel: links (no spaces or dashes)', max_length=20)),
                ('email', models.EmailField(default='equacare77@gmail.com', max_length=254)),
                ('street_address', models.CharField(default='7611 Douglas Ave #24', max_length=200)),
                ('city', models.CharField(default='Urbandale', max_length=100)),
                ('state', models.CharField(default='IA', max_length=2)),
                ('zip_code', models.CharField(default='50322-3076', max_length=20)),
                ('availability_text', models.CharField(default='Available 24/7', max_length=100)),
                ('facebook_url', models.URLField(blank=True, help_text='Full Facebook page URL')),
                ('twitter_url', models.URLField(blank=True, help_text='Full Twitter profile URL')),
                ('linkedin_url', models.URLField(blank=True, help_text='Full LinkedIn page URL')),
                ('instagram_url', models.URLField(blank=True, help_text='Full Instagram profile URL')),
                ('footer_about', models.TextField(default='Equacare LLC provides compassionate non-medical home care services to families in our community.', help_text='Brief description for footer')),
                ('copyright_text', models.CharField(default='© 2024 Equacare LLC. All rights reserved.', help_text='Copyright text in footer', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
