# Generated by Django 4.2.25 on 2025-10-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_joblisting_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='About Equacare', max_length=200)),
                ('subtitle', models.CharField(default='Non-medical home care services for families in our community', max_length=300)),
                ('paragraph_1', models.TextField(default="At Equacare, we understand that life can be challenging. That's why we provide compassionate, non-medical home care services to help you or your loved ones live comfortably and independently at home.")),
                ('paragraph_2', models.TextField(default="Our trained caregivers assist with everyday activities like personal care, meal preparation, light housekeeping, and companionship. We don't provide medical treatments or nursing care - we focus on the personal support that makes daily life easier.")),
                ('about_image', models.ImageField(help_text='Recommended size: 800x600px', upload_to='about/')),
                ('cta_title', models.CharField(default='Ready to Learn More?', max_length=200)),
                ('cta_text', models.TextField(default="Let's talk about how we can help you or your loved ones.")),
                ('button_text', models.CharField(default='Contact Us', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
    ]
