# Generated by Django 4.2.25 on 2025-10-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_aboutpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CEOSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(default='A Message from Our CEO', max_length=200)),
                ('ceo_name', models.CharField(default='[CEO Name]', help_text='Full name of the CEO', max_length=200)),
                ('ceo_title', models.CharField(default='Chief Executive Officer', max_length=100)),
                ('ceo_image', models.ImageField(blank=True, help_text='Optional: CEO photo (recommended size: 400x400px)', null=True, upload_to='ceo/')),
                ('paragraph_1', models.TextField(default='Welcome to Equacare LLC. We are truly honored that you have chosen us to be part of your care journey. At Equacare, our mission is to promote independence, dignity, comfort, and quality of life for each individual we serve.')),
                ('paragraph_2', models.TextField(default='Our team is dedicated to providing compassionate, reliable, and person-centered support in the comfort of your own home. We believe that with the right assistance, every person can enjoy the safety, familiarity, and meaningful connections of their home and community for as long as possible.')),
                ('paragraph_3', models.TextField(default='As a valued member, you are at the heart of everything we do. We are committed to respecting your rights, honoring your choices, and working closely with you and your family to support your unique needs and goals.')),
                ('paragraph_4', models.TextField(default='Thank you for placing your trust in Equacare LLC. We look forward to working together to make each day safe, comfortable, and meaningful.')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CEO Section',
                'verbose_name_plural': 'CEO Section',
            },
        ),
    ]
