# Generated by Django 4.2.25 on 2025-10-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_ceosection'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceosection',
            name='closing_text',
            field=models.CharField(default='Warm regards,', help_text='Closing line before signature', max_length=100),
        ),
        migrations.AddField(
            model_name='ceosection',
            name='signature_name',
            field=models.CharField(blank=True, help_text='Name for signature (leave blank to use CEO name)', max_length=200),
        ),
    ]
