# Generated by Django 4.2.25 on 2025-10-13 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_ceosection_closing_text_ceosection_signature_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title/name of the program or event', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description of the program/event')),
                ('photo', models.ImageField(help_text='Program/event photo (recommended size: 800x600px)', upload_to='programs/')),
                ('date', models.DateField(blank=True, help_text='Date of the program/event (optional)', null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which photos appear (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this photo from gallery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Program Gallery Photo',
                'verbose_name_plural': 'Program Gallery Photos',
                'ordering': ['display_order', '-date', '-created_at'],
            },
        ),
    ]
