# Generated by Django 4.2.25 on 2025-10-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_programgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='access_type',
            field=models.CharField(choices=[('download', 'Download'), ('view', 'View Only (Read-Only)')], default='download', help_text='Choose whether users can download or only view this document', max_length=20),
        ),
    ]
