# Generated by Django 4.2.25 on 2025-10-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_document_access_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(help_text='Upload any file type: PDF, Word, Excel, PowerPoint, Images, etc.', upload_to='documents/'),
        ),
    ]
