# Generated by Django 4.2.25 on 2025-10-15 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_delete_service_delete_testimonial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(blank=True, help_text='Leave blank for general applications', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='website.joblisting'),
        ),
    ]
