# Generated by Django 4.2.25 on 2025-10-15 22:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_jobapplication_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'We're Hiring!', 'Join Our Team', 'Career Opportunities Available'", max_length=200)),
                ('content', models.TextField(help_text='Description of available positions or hiring information')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Career Notice',
                'verbose_name_plural': 'Career Notices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='job',
        ),
        migrations.DeleteModel(
            name='JobListing',
        ),
    ]
