# Generated by Django 4.2.25 on 2025-10-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_careernotice_remove_jobapplication_job_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='Careers', max_length=200)),
                ('page_subtitle', models.CharField(default="Join a team that's about service, kindness, and respect", max_length=300)),
                ('intro_paragraph_1', models.TextField(default="Are you interested in working with us? Simply submit the application on this page. We'll review it now, and keep it on file for future openings.")),
                ('intro_paragraph_2', models.TextField(default="If you are the type of healthcare professional who takes pride in a job well done, our agency may be the right career move for you. We put the patient's needs first, but we also know that to give good service, you have to treat our caregivers well. Our first step in delivering excellent service to clients is to give the caregivers the support they need and the respect they deserve. If you would like to know about future job opportunities, simply use the form below to send your information.")),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Career Page',
                'verbose_name_plural': 'Career Page',
            },
        ),
    ]
