# Generated by Django 4.2.25 on 2025-10-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_careerpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='best_time',
            field=models.CharField(blank=True, max_length=200, verbose_name='Best time to call'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='current_employment',
            field=models.CharField(blank=True, max_length=300, verbose_name='Current employment'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='date_available',
            field=models.DateField(blank=True, null=True, verbose_name='Date available'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='degree_info',
            field=models.TextField(blank=True, verbose_name='Degree/Certification'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='employment_history',
            field=models.TextField(blank=True, verbose_name='Employment history'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='general_comments',
            field=models.TextField(blank=True, verbose_name='General comments'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='other_certifications',
            field=models.TextField(blank=True, verbose_name='Other certifications'),
        ),
    ]
